using YoutubeExplode.Converter;
using YoutubeExplode.Videos.Streams;

namespace ENTOS.Module.Utils
{
    public static class YouTubeUtils
    {
        /// <summary>
        ///   Download content from Youtube ( isVideo = true: Download Video has Audio, isVideo = false: Download only Audio, isVideo = null: Download silent Video)
        /// </summary>
        /// <summary>
        /// Tải nội dung từ YouTube
        /// </summary>
        /// <param name="videoUrl">URL video YouTube</param>
        /// <param name="saveFolder">Thư mục lưu file</param>
        /// <param name="isVideo">True: tải video có âm thanh, False: chỉ tải âm thanh, null: tải video không âm thanh</param>
        /// <param name="isSubtitle">True: tải phụ đề, False: kiểm tra phụ đề cuối</param>
        /// <returns>Đường dẫn file đã tải</returns>
        public static string DownloadFromYoutube(string videoUrl, string saveFolder, bool? isVideo = true, bool? isSubtitle = null)
        {
            var downloadTask = System.Threading.Tasks.Task.Run(() => DownloadFromYoutubeAsync(videoUrl, saveFolder, isVideo, isSubtitle));
            downloadTask.Wait();
            return downloadTask.Result;

        }


        /// <summary>
        ///   Download content from Youtube ( isVideo = true: Download Video has Audio, isVideo = false: Download only Audio, isVideo = null: Download silent Video, subtitle = true : Download Subtile, subtitle = false : Check EndSubtile)
        /// </summary>
        public static async System.Threading.Tasks.Task<string> DownloadFromYoutubeAsync(string videoUrl, string saveFolder, bool? isVideo = true, bool? subtitle = null)
        {
            var youtube = new YoutubeExplode.YoutubeClient();
            var videoId = YoutubeExplode.Videos.VideoId.Parse(videoUrl);
            var videoYoutube = await youtube.Videos.GetAsync(videoId);
            if (subtitle != null)
            {
                var trackManifest = await youtube.Videos.ClosedCaptions.GetManifestAsync(videoUrl);
                //2024-08-20: Chỉ lấy phụ đề có sãn, không lấy phụ đè tự sinh
                var trackInfo = trackManifest.Tracks?.FirstOrDefault(x => !x.IsAutoGenerated && x.Language.Code == "en");
                if (subtitle == false)
                {
                    if (trackInfo != null)
                        return trackInfo.Url;
                    else return null;
                }
                if (subtitle == true)
                {
                    if (trackInfo is null)
                        trackInfo = trackManifest.Tracks?.FirstOrDefault();
                    if (trackInfo != null)
                    {
                        var subTitlePath = $"{saveFolder}\\{System.Text.RegularExpressions.Regex.Replace(videoYoutube.Title, @"[^a-zA-Z0-9]", "")}.srt";
                        await youtube.Videos.ClosedCaptions.DownloadAsync(trackInfo, subTitlePath);
                        return subTitlePath;
                    }
                }

                return null;
            }
            var streamManifest = await youtube.Videos.Streams.GetManifestAsync(videoId);
            //var streamInfo = streamManifest.GetMuxedStreams().GetWithHighestVideoQuality();
            if (isVideo == null)
            {
                var videoStreamInfo = streamManifest.GetVideoStreams().Where(s => s.Container == YoutubeExplode.Videos.Streams.Container.Mp4).GetWithHighestVideoQuality();
                // Get the actual stream
                var videostream = await youtube.Videos.Streams.GetAsync(videoStreamInfo);
                var videoPath = $"{saveFolder}\\{System.Text.RegularExpressions.Regex.Replace(Module.Helpers.TextHelper.RemoveUnicode(videoYoutube.Title), @"[^a-zA-Z0-9]", "")}-Video.{videoStreamInfo.Container}";
                await youtube.Videos.Streams.DownloadAsync(videoStreamInfo, videoPath);
                return videoPath;
            }
            else if (isVideo == false)
            {
                var audioStreamInfo = streamManifest.GetAudioOnlyStreams().Where(s => s.Container == YoutubeExplode.Videos.Streams.Container.Mp4 || s.Container == YoutubeExplode.Videos.Streams.Container.Mp3).GetWithHighestBitrate();
                // Get the actual stream
                var audiostream = await youtube.Videos.Streams.GetAsync(audioStreamInfo);
                var audioPath = $"{saveFolder}\\{System.Text.RegularExpressions.Regex.Replace(Module.Helpers.TextHelper.RemoveUnicode(videoYoutube.Title), @"[^a-zA-Z0-9]", "")}-Audio.{audioStreamInfo.Container}";
                await youtube.Videos.Streams.DownloadAsync(audioStreamInfo, audioPath);
                return audioPath;
            }
            else
            {
                //video
                var videoStreamInfo = streamManifest.GetVideoStreams().Where(s => s.Container == YoutubeExplode.Videos.Streams.Container.Mp4).GetWithHighestVideoQuality();
                var videostream = await youtube.Videos.Streams.GetAsync(videoStreamInfo);
                var videoPath = $"{saveFolder}\\{System.Text.RegularExpressions.Regex.Replace(Module.Helpers.TextHelper.RemoveUnicode(videoYoutube.Title), @"[^a-zA-Z0-9]", "")}.{videoStreamInfo.Container}";
                //audio
                var audioStreamInfo = streamManifest.GetAudioOnlyStreams().Where(s => s.Container == YoutubeExplode.Videos.Streams.Container.Mp4 || s.Container == YoutubeExplode.Videos.Streams.Container.Mp3).GetWithHighestBitrate();
                var audiostream = await youtube.Videos.Streams.GetAsync(audioStreamInfo);
                //var audioPath = $"{saveFolder}\\{videoYoutube.Title}.{audioStreamInfo.Container}";
                //Trộn 2 luồng               
                var streamInfos = new YoutubeExplode.Videos.Streams.IStreamInfo[] { audioStreamInfo, videoStreamInfo };

                await youtube.Videos.DownloadAsync(streamInfos, new YoutubeExplode.Converter.ConversionRequestBuilder(videoPath).Build());
                return videoPath;
            }
            //var trackManifest = await youtube.Videos.ClosedCaptions.GetManifestAsync(videoUrl);

        }


        /// <summary>
        ///   Download content from Youtube ( isVideo = true: Download Video has Audio, isVideo = false: Download only Audio, isVideo = null: Download silent Video)
        /// </summary>
        public static async System.Threading.Tasks.Task<string> GetPlayingUrlFromYoutubeAsync(string videoUrl)
        {
            var youtube = new YoutubeExplode.YoutubeClient();
            var videoId = YoutubeExplode.Videos.VideoId.Parse(videoUrl);
            var videoYoutube = await youtube.Videos.GetAsync(videoId);

            var streamManifest = await youtube.Videos.Streams.GetManifestAsync(videoId);
            var streamInfo = streamManifest.GetMuxedStreams().GetWithHighestVideoQuality();
            return streamInfo.Url;
        }

        public static async System.Threading.Tasks.Task<string> YoutubeTranscript(string videoUrl, string saveFile)
        {
            var videoId = YoutubeExplode.Videos.VideoId.TryParse(videoUrl);
            if (videoId is null)
                return null;
            var youTubeTranscriptApi = new YoutubeTranscriptApi.YouTubeTranscriptApi();
            try
            {
                var transcriptItems = youTubeTranscriptApi.GetTranscript(videoId, new[] { "en", "vi" });
                if (transcriptItems.Count() > 0)
                {
                    string subtitleText = "";
                    //var subtitleWithSort = video.AudioList.OrderBy(m => m.Start);
                    int index = 1;
                    foreach (var transcriptItem in transcriptItems)
                    {
                        var textValue = transcriptItem.Text;
                        if (!string.IsNullOrEmpty(textValue) && transcriptItem.Start > 0)
                        {
                            subtitleText += index.ToString("D");
                            subtitleText += System.Environment.NewLine;
                            subtitleText += string.Format("{0} --> {1}", System.TimeSpan.FromMilliseconds(transcriptItem.Start).ToString(@"hh\:mm\:ss\,fff"), System.TimeSpan.FromMilliseconds(transcriptItem.Start + transcriptItem.Duration).ToString(@"hh\:mm\:ss\,fff"));
                            subtitleText += System.Environment.NewLine;
                            subtitleText += textValue;
                            subtitleText += System.Environment.NewLine;
                            subtitleText += System.Environment.NewLine;
                            index++;
                        }
                    }
                    if (!string.IsNullOrEmpty(subtitleText))
                    {
                        System.IO.File.WriteAllText(saveFile, subtitleText);
                        return saveFile;
                    }
                }

            }
            catch (System.Exception)
            {

            }
            return null;
        }

        /// <summary>
        /// Kiểm tra URL có phải là YouTube không
        /// </summary>
        /// <param name="url">URL cần kiểm tra</param>
        /// <returns>True nếu là URL YouTube</returns>
        public static bool IsYoutubeUrl(string url)
        {
            if (!string.IsNullOrEmpty(url))
            {
                if (url.Contains("youtube.com", StringComparison.OrdinalIgnoreCase) || url.Contains("youtu.be", StringComparison.OrdinalIgnoreCase))
                    return true;
            }
            return false;


        }

        public static string DownloadFromYoutubeWithSubtitles(string videoUrl, string saveFolder, bool? isVideo = true, bool? isSubtitle = null, bool isAutoGenerated = false, string languageCode = "en")
        {
            var downloadTask = System.Threading.Tasks.Task.Run(() => DownloadFromYoutubeAsync(videoUrl, saveFolder, isVideo, isSubtitle, isAutoGenerated, languageCode));
            downloadTask.Wait();
            return downloadTask.Result;

        }



        public static async System.Threading.Tasks.Task<string> DownloadFromYoutubeAsync(string videoUrl, string saveFolder, bool? isVideo = true, bool? subtitle = null, bool isAutoGenerated = false, string languageCode = "en")
        {
            var youtube = new YoutubeExplode.YoutubeClient();
            var videoId = YoutubeExplode.Videos.VideoId.Parse(videoUrl);
            var videoYoutube = await youtube.Videos.GetAsync(videoId);
            if (subtitle != null)
            {
                var trackManifest = await youtube.Videos.ClosedCaptions.GetManifestAsync(videoUrl);
                if (trackManifest.Tracks.FirstOrDefault(x => !x.IsAutoGenerated) == null && !isAutoGenerated)
                {
                    subtitle = false;
                }
                //2025-05-31: Lấy phụ đề tùy theo lựa chọn
                var trackInfo = trackManifest.Tracks?.FirstOrDefault(x => !x.IsAutoGenerated && x.Language.Code.StartsWith(languageCode));
                if (!isAutoGenerated && trackInfo == null && trackManifest != null)
                {
                    subtitle = false;
                }
                if (isAutoGenerated)
                    trackInfo = trackManifest.Tracks?.FirstOrDefault(x => x.IsAutoGenerated);

                if (subtitle == false)
                {
                    if (trackInfo != null)
                        return trackInfo.Url;
                    else return null;
                }
                if (subtitle == true)
                {
                    if (trackInfo is null)
                        trackInfo = trackManifest.Tracks?.FirstOrDefault();
                    if (trackInfo != null)
                    {
                        var subTitlePath = $"{saveFolder}\\{Module.Helpers.FileSystemHelper.GetValidFileName(videoYoutube.Title).Replace("   ", " ").Replace("  ", " ")}.srt";
                        await youtube.Videos.ClosedCaptions.DownloadAsync(trackInfo, subTitlePath);
                        return subTitlePath;
                    }
                }

                return null;
            }
            var streamManifest = await youtube.Videos.Streams.GetManifestAsync(videoId);
            //var streamInfo = streamManifest.GetMuxedStreams().GetWithHighestVideoQuality();
            if (isVideo == null)
            {
                var videoStreamInfo = streamManifest.GetVideoStreams().Where(s => s.Container == YoutubeExplode.Videos.Streams.Container.Mp4).GetWithHighestVideoQuality();
                // Get the actual stream
                var videostream = await youtube.Videos.Streams.GetAsync(videoStreamInfo);
                var videoPath = $"{saveFolder}\\{Module.Helpers.FileSystemHelper.GetValidFileName(videoYoutube.Title).Replace("   ", " ").Replace("  ", " ")}-Video.{videoStreamInfo.Container}";
                await youtube.Videos.Streams.DownloadAsync(videoStreamInfo, videoPath);
                return videoPath;
            }
            else if (isVideo == false)
            {
                var audioStreamInfo = streamManifest.GetAudioOnlyStreams().Where(s => s.Container == YoutubeExplode.Videos.Streams.Container.Mp4 || s.Container == YoutubeExplode.Videos.Streams.Container.Mp3).GetWithHighestBitrate();
                // Get the actual stream
                var audiostream = await youtube.Videos.Streams.GetAsync(audioStreamInfo);
                var audioPath = $"{saveFolder}\\{Module.Helpers.FileSystemHelper.GetValidFileName(videoYoutube.Title).Replace("   ", " ").Replace("  ", " ")}-Audio.{audioStreamInfo.Container}";
                await youtube.Videos.Streams.DownloadAsync(audioStreamInfo, audioPath);
                return audioPath;
            }
            else
            {
                //video
                var videoStreamInfo = streamManifest.GetVideoStreams().Where(s => s.Container == YoutubeExplode.Videos.Streams.Container.Mp4).GetWithHighestVideoQuality();
                var videostream = await youtube.Videos.Streams.GetAsync(videoStreamInfo);
                var videoPath = $"{saveFolder}\\{Module.Helpers.FileSystemHelper.GetValidFileName(videoYoutube.Title).Replace("   ", " ").Replace("  ", " ")}.{videoStreamInfo.Container}";
                //audio
                var audioStreamInfo = streamManifest.GetAudioOnlyStreams().Where(s => s.Container == YoutubeExplode.Videos.Streams.Container.Mp4 || s.Container == YoutubeExplode.Videos.Streams.Container.Mp3).GetWithHighestBitrate();
                var audiostream = await youtube.Videos.Streams.GetAsync(audioStreamInfo);
                //var audioPath = $"{saveFolder}\\{videoYoutube.Title}.{audioStreamInfo.Container}";
                //Trộn 2 luồng               
                var streamInfos = new YoutubeExplode.Videos.Streams.IStreamInfo[] { audioStreamInfo, videoStreamInfo };

                await youtube.Videos.DownloadAsync(streamInfos, new YoutubeExplode.Converter.ConversionRequestBuilder(videoPath).Build());
                return videoPath;
            }
            //var trackManifest = await youtube.Videos.ClosedCaptions.GetManifestAsync(videoUrl);
        }
        public static async Task<YoutubeExplode.Videos.ClosedCaptions.ClosedCaptionManifest> GetTrackCaptionManifest(string videoUrl)
        {
            var youtube = new YoutubeExplode.YoutubeClient();
            var videoId = YoutubeExplode.Videos.VideoId.Parse(videoUrl);
            var trackManifest = await youtube.Videos.ClosedCaptions.GetManifestAsync(videoId);
            return trackManifest;
            //Module.Helpers.LogHelper.Info(logMessage + " - End");
        }
    }
}